defaults write com.apple.Terminal NSWindowTabbingShoudShowTabBarKey-TTWindow-TTWindowController-TTWindowController-VT-FS -bool true

/usr/libexec/PlistBuddy -c "Delete 'Window Settings':Basic:columnCount" ~/Library/Preferences/com.apple.Terminal.plist 2> /dev/null
/usr/libexec/PlistBuddy -c "Add 'Window Settings':Basic:columnCount integer 130" ~/Library/Preferences/com.apple.Terminal.plist
/usr/libexec/PlistBuddy -c "Delete 'Window Settings':Basic:rowCount" ~/Library/Preferences/com.apple.Terminal.plist 2> /dev/null
/usr/libexec/PlistBuddy -c "Add 'Window Settings':Basic:rowCount integer 40" ~/Library/Preferences/com.apple.Terminal.plist

/usr/libexec/PlistBuddy -c "Delete 'Window Settings':Basic:ShowActiveProcessInTitle" ~/Library/Preferences/com.apple.Terminal.plist 2> /dev/null
/usr/libexec/PlistBuddy -c "Add 'Window Settings':Basic:ShowActiveProcessInTitle bool false" ~/Library/Preferences/com.apple.Terminal.plist
/usr/libexec/PlistBuddy -c "Delete 'Window Settings':Basic:ShowDimensionsInTitle" ~/Library/Preferences/com.apple.Terminal.plist 2> /dev/null
/usr/libexec/PlistBuddy -c "Add 'Window Settings':Basic:ShowDimensionsInTitle bool false" ~/Library/Preferences/com.apple.Terminal.plist

/usr/libexec/PlistBuddy -c "Delete 'Window Settings':Basic:ShowRepresentedURLInTabTitle" ~/Library/Preferences/com.apple.Terminal.plist 2> /dev/null
/usr/libexec/PlistBuddy -c "Add 'Window Settings':Basic:ShowRepresentedURLInTabTitle bool false" ~/Library/Preferences/com.apple.Terminal.plist

/usr/libexec/PlistBuddy -c "Delete 'Window Settings':Basic:shellExitAction" ~/Library/Preferences/com.apple.Terminal.plist 2> /dev/null
/usr/libexec/PlistBuddy -c "Add 'Window Settings':Basic:shellExitAction integer 1" ~/Library/Preferences/com.apple.Terminal.plist

/usr/libexec/PlistBuddy -c "Delete 'Window Settings':Basic:VisualBellOnlyWhenMuted" ~/Library/Preferences/com.apple.Terminal.plist 2> /dev/null
/usr/libexec/PlistBuddy -c "Add 'Window Settings':Basic:VisualBellOnlyWhenMuted bool false" ~/Library/Preferences/com.apple.Terminal.plist

base64 -D > /tmp/data.plist <<EOF
YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZlctEICVRyb290gAGkCwwVFlUkbnVsbNQNDg8QERITFFZOU1NpemVYTlNmRmxhZ3NWTlNOYW1lViRjbGFzcyNAKAAAAAAAABAQgAKAA15TRk1vbm8tUmVndWxhctIXGBkaWiRjbGFzc25hbWVYJGNsYXNzZXNWTlNGb250ohkbWE5TT2JqZWN0CBEaJCkyN0lMUVNYXmdud36FjpCSlKOos7zDxgAAAAAAAAEBAAAAAAAAABwAAAAAAAAAAAAAAAAAAADP
EOF
/usr/libexec/PlistBuddy -c "Import 'Window Settings':Basic:Font /tmp/data.plist" ~/Library/Preferences/com.apple.Terminal.plist

base64 -D > /tmp/data.plist <<EOF
YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZlctEICVRyb290gAGmCwwXGxwjVSRudWxs1Q0ODxAREhMUFRZcTlNDb21wb25lbnRzVU5TUkdCXE5TQ29sb3JTcGFjZV8QEk5TQ3VzdG9tQ29sb3JTcGFjZVYkY2xhc3NPECgwLjExNzY0NzA1ODggMC4xMTc2NDcwNTg4IDAuMTE3NjQ3MDU4OCAxTxAqMC4wOTcxNTE2OTY2OCAwLjA5NzE1MTY5NjY4IDAuMDk3MTUxNjk2NjgAEAGAAoAF0hgRGRpVTlNJQ0OAA4AETxECCAAAAghhcHBsBAAAAG1udHJSR0IgWFlaIAfmAAwABwATADkAI2Fjc3BBUFBMAAAAAEFQUEwAAAAAAAAAAAAAAAAAAAAAAAD21gABAAAAANMtYXBwbFc51QI+UOYF+sS0S7T/efoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACmRlc2MAAAD8AAAALmNwcnQAAAEsAAAAUHd0cHQAAAF8AAAAFHJYWVoAAAGQAAAAFGdYWVoAAAGkAAAAFGJYWVoAAAG4AAAAFHJUUkMAAAHMAAAAEGNoYWQAAAHcAAAALGJUUkMAAAHMAAAAEGdUUkMAAAHMAAAAEG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAEgAAABwATABHACAASABEAFIAIAA0AEsAAG1sdWMAAAAAAAAAAQAAAAxlblVTAAAANAAAABwAQwBvAHAAeQByAGkAZwBoAHQAIABBAHAAcABsAGUAIABJAG4AYwAuACwAIAAyADAAMgAyWFlaIAAAAAAAAPbWAAEAAAAA0y1YWVogAAAAAAAAftQAADnfAAAAwFhZWiAAAAAAAABR0QAAuYQAABCsWFlaIAAAAAAAACYxAAAMnQAAwcFwYXJhAAAAAAAAAAAAAfYEc2YzMgAAAAAAAQxyAAAF+P//8x0AAAe6AAD9cv//+53///2kAAAD2QAAwHHSHR4fIFokY2xhc3NuYW1lWCRjbGFzc2VzXE5TQ29sb3JTcGFjZaIhIlxOU0NvbG9yU3BhY2VYTlNPYmplY3TSHR4kJVdOU0NvbG9yoiQiAAgAEQAaACQAKQAyADcASQBMAFEAUwBaAGAAawB4AH4AiwCgAKcA0gD/AQEBAwEFAQoBEAESARQDIAMlAzADOQNGA0kDVgNfA2QDbAAAAAAAAAIBAAAAAAAAACYAAAAAAAAAAAAAAAAAAANv
EOF
/usr/libexec/PlistBuddy -c "Import 'Window Settings':Basic:BackgroundColor /tmp/data.plist" ~/Library/Preferences/com.apple.Terminal.plist

base64 -D > /tmp/data.plist <<EOF
YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZlctEICVRyb290gAGmCwwXGxwjVSRudWxs1Q0ODxAREhMUFRZcTlNDb21wb25lbnRzVU5TUkdCXE5TQ29sb3JTcGFjZV8QEk5TQ3VzdG9tQ29sb3JTcGFjZVYkY2xhc3NHMSAxIDEgMUYxIDEgMQAQAYACgAXSGBEZGlVOU0lDQ4ADgARPEQIIAAACCGFwcGwEAAAAbW50clJHQiBYWVogB+YADAAIAAsAKQAKYWNzcEFQUEwAAAAAQVBQTAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1hcHBscQLvtb5J1YoqPykuALwMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKZGVzYwAAAPwAAAAuY3BydAAAASwAAABQd3RwdAAAAXwAAAAUclhZWgAAAZAAAAAUZ1hZWgAAAaQAAAAUYlhZWgAAAbgAAAAUclRSQwAAAcwAAAAQY2hhZAAAAdwAAAAsYlRSQwAAAcwAAAAQZ1RSQwAAAcwAAAAQbWx1YwAAAAAAAAABAAAADGVuVVMAAAASAAAAHABMAEcAIABIAEQAUgAgADQASwAAbWx1YwAAAAAAAAABAAAADGVuVVMAAAA0AAAAHABDAG8AcAB5AHIAaQBnAGgAdAAgAEEAcABwAGwAZQAgAEkAbgBjAC4ALAAgADIAMAAyADJYWVogAAAAAAAA9tYAAQAAAADTLVhZWiAAAAAAAAB+1AAAOd8AAADAWFlaIAAAAAAAAFHRAAC5hAAAEKxYWVogAAAAAAAAJjEAAAydAADBwXBhcmEAAAAAAAAAAAAB9gRzZjMyAAAAAAABDHIAAAX4///zHQAAB7oAAP1y///7nf///aQAAAPZAADAcdIdHh8gWiRjbGFzc25hbWVYJGNsYXNzZXNcTlNDb2xvclNwYWNloiEiXE5TQ29sb3JTcGFjZVhOU09iamVjdNIdHiQlV05TQ29sb3KiJCIACAARABoAJAApADIANwBJAEwAUQBTAFoAYABrAHgAfgCLAKAApwCvALYAuAC6ALwAwQDHAMkAywLXAtwC5wLwAv0DAAMNAxYDGwMjAAAAAAAAAgEAAAAAAAAAJgAAAAAAAAAAAAAAAAAAAyY=
EOF
/usr/libexec/PlistBuddy -c "Import 'Window Settings':Basic:TextColor /tmp/data.plist" ~/Library/Preferences/com.apple.Terminal.plist
/usr/libexec/PlistBuddy -c "Import 'Window Settings':Basic:TextBoldColor /tmp/data.plist" ~/Library/Preferences/com.apple.Terminal.plist

base64 -D > /tmp/data.plist <<EOF
YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZlctEICVRyb290gAGmCwwXGxwjVSRudWxs1Q0ODxAREhMUFRZcTlNDb21wb25lbnRzVU5TUkdCXE5TQ29sb3JTcGFjZV8QEk5TQ3VzdG9tQ29sb3JTcGFjZVYkY2xhc3NPECgwLjI0NzA1ODgyMzUgMC4zODgyMzUyOTQxIDAuNTQ1MDk4MDM5MiAxTxAnMC4xOTM4NjYzMjc0IDAuMzUzNzEwOTE5NiAwLjUyNTQ1NjM2ODkAEAGAAoAF0hgRGRpVTlNJQ0OAA4AETxECCAAAAghhcHBsBAAAAG1udHJSR0IgWFlaIAfmAAwABwATADkAI2Fjc3BBUFBMAAAAAEFQUEwAAAAAAAAAAAAAAAAAAAAAAAD21gABAAAAANMtYXBwbFc51QI+UOYF+sS0S7T/efoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACmRlc2MAAAD8AAAALmNwcnQAAAEsAAAAUHd0cHQAAAF8AAAAFHJYWVoAAAGQAAAAFGdYWVoAAAGkAAAAFGJYWVoAAAG4AAAAFHJUUkMAAAHMAAAAEGNoYWQAAAHcAAAALGJUUkMAAAHMAAAAEGdUUkMAAAHMAAAAEG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAEgAAABwATABHACAASABEAFIAIAA0AEsAAG1sdWMAAAAAAAAAAQAAAAxlblVTAAAANAAAABwAQwBvAHAAeQByAGkAZwBoAHQAIABBAHAAcABsAGUAIABJAG4AYwAuACwAIAAyADAAMgAyWFlaIAAAAAAAAPbWAAEAAAAA0y1YWVogAAAAAAAAftQAADnfAAAAwFhZWiAAAAAAAABR0QAAuYQAABCsWFlaIAAAAAAAACYxAAAMnQAAwcFwYXJhAAAAAAAAAAAAAfYEc2YzMgAAAAAAAQxyAAAF+P//8x0AAAe6AAD9cv//+53///2kAAAD2QAAwHHSHR4fIFokY2xhc3NuYW1lWCRjbGFzc2VzXE5TQ29sb3JTcGFjZaIhIlxOU0NvbG9yU3BhY2VYTlNPYmplY3TSHR4kJVdOU0NvbG9yoiQiAAgAEQAaACQAKQAyADcASQBMAFEAUwBaAGAAawB4AH4AiwCgAKcA0gD8AP4BAAECAQcBDQEPAREDHQMiAy0DNgNDA0YDUwNcA2EDaQAAAAAAAAIBAAAAAAAAACYAAAAAAAAAAAAAAAAAAANs
EOF
/usr/libexec/PlistBuddy -c "Import 'Window Settings':Basic:SelectionColor /tmp/data.plist" ~/Library/Preferences/com.apple.Terminal.plist

rm /tmp/data.plist
