script "hostname"

tap "fluxcd/tap"
tap "int128/kubelogin"

brew "bundler-completion"
brew "cilium-cli"
brew "fluxcd/tap/flux"
brew "gem-completion"
brew "graphicsmagick"
brew "helm"
brew "int128/kubelogin/kubelogin"
brew "libffi"
brew "libyaml"
brew "mysql-client@5.7"
brew "openshift-cli"
brew "ruby-completion"
brew "tektoncd-cli"
brew "terraform"

cask "bitwarden"
cask "mongodb-compass"
cask "postman"
cask "rubymine"
cask "sequel-ace"
